### ISSUE TITLE
Frequency Scaling issue..

### ISSUE THREAD

**Issue by kirananto** [CyanogenMod/android_kernel_cyanogen_msm8916#1]
The cpu scaling is not proper..
When compiled and run on yureka
the cores tend to always stick on to highest frequency given from userspace(set by user)

**Comment by shskyinfo** [comment]
+1 same issue for Yuphoria
CPU always stays at max freq

**Comment by ajaichemmanam** [comment]
+1 Need to fix the issue soon...

**Comment by BharatwajRao** [comment]
+1 need to be fixed

**Comment by mnkgyl** [comment]
+1 

Should be fixed ASAP.

**Comment by shskyinfo** [comment]
Can someone please fix this?
